### ISSUE TITLE
Plugin version displayed in readme is bugged

### ISSUE THREAD

**Issue by pitininja** [drone-plugins/sonarqube-scanner#88]
Hello,

Thanks for your work on this plugin.

In the readme of the `master` branch (the one displayed by default on this repo) it's said to setup the plugin with version `v2.0.2-java17`.

However the Docker image tagged `v2.0.2-java17` contains a bug : the Sonarqube token is not properly base64 encoded when sent to the API in the Authorization header. Therefore the API requests to check the job status fail into 401.

To fix this issue one must set the plugin image to `latest` (`image: plugins/sonarqube-scanner:latest`). The latest image works as the bug I described has been fixed in https://github.com/drone-plugins/sonarqube-scanner/commit/281ae96b9df27d787323f800b54eeb9dc8028135.

It would be great to either :

* Removing the `v2.0.2-java17` tag in the readme examples to avoid user getting misleaded
* Creating a new release and modifying the readme accordingly with a working tag

Regards

**Comment by diegopereiraeng** [comment]
Hi @pitininja sorry for the delay on this.

I've just fixed the README with the latest newer version, and i'm planning to update the latest tag soon.

Sorry for the inconvenience
